# Definindo o nome do Workflow
name: Meu primeiro workflow no github actions

# Definindo quando o workflow vai ser disparado
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Definindo os jobs que o workflow executará
jobs:
  job01:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Executando um comando simples
      run: echo "Ola Mundo! Esse é o primeiro job no GitHub Actions"

    - name: Step 2
      run: echo "Executando Step 2"
